# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
- repo: self

queue:
  name: PIC POOL

trigger:

  branches:
    include:
    - master
    
steps:

- script:
    npm install -g npm@latest
  displayName: 'Install npm lastest globally'

- script:
    npm install -g @angular/cli
  displayName: 'Install @angular/cli globally'

- script:
    npm install
  displayName: 'Install packages dependencies'

- script:
    npm run build
  displayName: 'Build application'

- task: CopyFiles@2
  displayName: 'Copy sources (binaries)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\dist'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: '$(build.definitionname)'

    
  
