# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
- repo: self

queue:
  name: PIC POOL

trigger:

  branches:
    include:
    - passageEnCore
    
steps:

# - script:
#     npm install -g npm@latest
#   displayName: 'Install npm lastest globally'

- script:
    npm install -g @angular/cli
  displayName: 'Install @angular/cli globally'

- script:
    npm install
  displayName: 'Install packages dependencies'

- script:
    npm run build
  displayName: 'Build application'

- task: CopyFiles@2
  displayName: 'Copy sources (binaries)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\dist'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: '$(build.definitionname)'

- task: rvo.SendEmailTask.send-email-build-task.SendEmail@1
  displayName: 'Send an email with subject Erreur dans l’exécution du pipeline de build $(Build.DefinitionName)'
  inputs:
    To: 'g.mace@imaprotect.fr,b.kerviche@imaprotect.fr,a.breneliere@imaprotect.fr'
    From: 'noreply@imaprotect.fr'
    Subject: 'Erreur dans l’exécution du pipeline de build $(Build.DefinitionName)'
    Body: |
     Une erreur a eu lieu durant l’exécution du pipeline de build $(Build.DefinitionName) : $(Build.BuildUri)
     
    SmtpServer: 'mail-app.imatech.intra'
    SmtpPort: 25
    UseSSL: false
  condition: failed()

