# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
- repo: self

queue:
  name: PIC POOL
  
steps:

- script: 
    ng build --prod --configuration=recette
  displayName: 'ng build'
